// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.DBContext;

namespace Repository.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20200515131851_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Faculty", b =>
                {
                    b.Property<string>("FacultyId");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("Designation");

                    b.Property<string>("Email");

                    b.Property<string>("FacultyName");

                    b.Property<string>("Shift");

                    b.Property<string>("Subject");

                    b.HasKey("FacultyId");

                    b.ToTable("FacultyTable");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("RollNo");

                    b.Property<string>("Class");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("Email");

                    b.Property<string>("Stream");

                    b.Property<string>("StudentName");

                    b.HasKey("RollNo");

                    b.ToTable("StudentTable");
                });
#pragma warning restore 612, 618
        }
    }
}
